services:
  web:
    build: .
    container_name: django_mvt_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: django_mvt_db
    environment:
      POSTGRES_DB: university_db
      POSTGRES_USER: university_user
      POSTGRES_PASSWORD: university_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U university_user -d university_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
